export const googleBucket = "https://storage.googleapis.com/giantsfanzine.co.uk/";
export const imagePath = googleBucket + "images/";
export const localUrl = window.location.protocol + "//" + window.location.host;
export const personImagePath = imagePath + "people/full/";
export const teamImagePath = imagePath + "teams/";
export const gameImagePath = imagePath + "games/";
export const groundImagePath = imagePath + "grounds/";
export const layoutImagePath = imagePath + "layout/";
export const competitionImagePath = imagePath + "competitions/";
